/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Placeholder Group payload. ADR-0010 G-hybrid will extend this with
         *     `parent_id`, `label`, `color`, `visibility`, `locked`, `order`.
         */
        Group: {
            /** @description Stable identifier for the group node within a Canvas Layout tree. */
            id: string;
        };
        /**
         * @description Placeholder Panel payload. The real schema adds geometry, z-order,
         *     visibility, lock, label, note, and parent linkage (ADR-0010).
         */
        Panel: {
            /** @description Stable identifier for the panel node within a Canvas Layout tree. */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
